spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/sentiment-api-db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:sentiment-api-pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

python:
  service:
    url: ${PYTHON_SERVICE_URL:http://localhost:3000/predict}